name: Node.js CI

on:
    push:
        branches: [trunk]
    pull_request:
        branches: [trunk]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - run: npm ci
            - run: npm run build
            - run: npm test
            - run: npm version prerelease --preid=ci-$GITHUB_RUN_ID --no-git-tag-version
            - run: npm pack

            - name: Upload
              uses: actions/upload-artifact@v2
              with:
                  name: package
                  path: '*.tgz'

    build-storybook:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.1
              with:
                  persist-credentials: false
            - name: Install and Build Storybook
              run: | # Install npm packages and build the Storybook files
                  npm install
                  npm run build-storybook
            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@3.6.2
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: trunk # The branch the action should deploy to.
                  FOLDER: docs-build # The folder that the build-storybook script generates files.
                  CLEAN: true # Automatically remove deleted files from the deploy branch
                  TARGET_FOLDER: docs # The folder that we serve our Storybook files from

    publish:
        name: 'Publish to GitHub Packages'
        needs: [build]
        runs-on: ubuntu-18.04
        steps:
            - name: Upload
              uses: actions/download-artifact@v2
              with:
                  name: package
            - uses: actions/setup-node@v1
              with:
                  node-version: 14.x
                  registry-url: https://npm.pkg.github.com/
                  scope: '@spiffdog-design'
            - run: echo "registry=https://npm.pkg.github.com/@spiffdog-design" >> .npmrc
            - run: npm publish $(ls *.tgz)
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
